### ISSUE TITLE
Missing Gateway Setting for certain existing APPs

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#402]
**Description:**
In gateway settings, seems to not be pulling the APPs (existing ones) right gateway info/details.

**Step by Step**

1. Find an existing APP (like one created weeks ago).
2. Click on the gateway settings button.
3. When prompted to the gateway details page, notice that the APPs icon have changed, there's no APP name, no APP keys, endpoints, nothing.

**Evidence:**
https://www.loom.com/share/059c2cc8900748d3b15f151564062304)

**Comment by nymd** [comment]
Due to changes in the system, we can't guarantee support for existing apps.

Since all applications in the production system have been created manually for Gateway use, no one is currently using the Dashboard apps and this won't affect anything in production. If any existing apps in production are affected, the fix will be in the database and not in the code.

Closing as non-issue.
